import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateHistoryPDF(item) {

    if (!item) return;

    const doc = new jsPDF();

    /* ===========================
       Title
    =========================== */

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(30, 64, 175);

    doc.text(
        "AI Textile Waste Analysis Report",
        105,
        18,
        { align: "center" }
    );

    doc.setFontSize(11);
    doc.setTextColor(120);

    doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        14,
        30
    );

    /* ===========================
       Basic Information
    =========================== */

    autoTable(doc, {

        startY: 40,

        head: [["Basic Information", "Value"]],

        body: [

            ["Image", item.image_name],

            ["Material", item.material],

            ["Material Confidence",
                `${(item.material_confidence * 100).toFixed(1)}%`],

            ["Damage", item.damage],

            ["Damage Confidence",
                `${(item.damage_confidence * 100).toFixed(1)}%`],

            ["Quality Grade", item.quality_grade],

            ["Quality Score", item.quality_score],

            ["Recommendation", item.recommended_action],

            ["Date",
                new Date(item.analyzed_at).toLocaleString()]

        ],

        theme: "grid",

        headStyles: {

            fillColor: [37, 99, 235]

        }

    });

    /* ===========================
       Material Classification
    =========================== */

    autoTable(doc, {

        startY: doc.lastAutoTable.finalY + 12,

        head: [["Material Classification", "Value"]],

        body: [

            ["Material Category", item.material_category],

            ["Fiber Composition", item.fiber_composition],

            ["Blend Identification", item.blend_identification],

            ["Fabric Texture", item.fabric_texture],

            ["Fabric Pattern", item.fabric_pattern]

        ],

        theme: "grid",

        headStyles: {

            fillColor: [99, 102, 241]

        }

    });

    /* ===========================
       Waste Classification
    =========================== */

    let wasteStart = doc.lastAutoTable.finalY + 12;

    if (wasteStart > 190) {

        doc.addPage();

        wasteStart = 20;

    }

    autoTable(doc, {

        startY: wasteStart,

        head: [["Waste Classification", "Value"]],

        body: [

            ["Category", item.waste_category],

            ["Recyclability", item.recyclability],

            ["Reuse Potential", item.reuse_potential],

            ["Contamination", item.contamination_detection],

            ["Disposal", item.disposal_recommendation],

            ["Compostable", item.compostable],

            ["Hazardous Textile", item.hazardous_textile]

        ],

        theme: "grid",

        headStyles: {

            fillColor: [59, 130, 246]

        }

    });

    /* ===========================
       Recycling Recommendation
    =========================== */

    let recycleStart = doc.lastAutoTable.finalY + 12;

    if (recycleStart > 190) {

        doc.addPage();

        recycleStart = 20;

    }

    autoTable(doc, {

        startY: recycleStart,

        head: [["Recycling Recommendation", "Value"]],

        body: [

            ["Recommended Method", item.recommended_method],

            ["Fiber Recycling", item.fiber_recycling],

            ["Mechanical Recycling", item.mechanical_recycling],

            ["Chemical Recycling", item.chemical_recycling],

            ["Fabric Reuse", item.fabric_reuse],

            ["Industrial Recovery", item.industrial_recovery],

            ["Donation", item.donation],

            ["Estimated Value", item.estimated_value],

            ["Environmental Impact", item.environmental_impact],

            ["Priority", item.priority],

            ["Waste Reduction Strategy",
                item.waste_reduction_strategy],

            ["Upcycling Suggestions",
                item.upcycling_suggestions]

        ],

        theme: "grid",

        headStyles: {

            fillColor: [22, 163, 74]

        }

    });

    /* ===========================
       Footer
    =========================== */

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(

        "Generated by Textile Waste Intelligence Platform",

        105,

        285,

        {

            align: "center"

        }

    );

    doc.save(

        `Analysis_Report_${item.id}.pdf`

    );

}